/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'

const ChatSessionIdLazyRouteImport = createFileRoute('/chat/$sessionId')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdLazyRoute = ChatSessionIdLazyRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/chat/$sessionId.lazy').then((d) => d.Route),
)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/$sessionId': typeof ChatSessionIdLazyRoute
  '/api/chat/': typeof ApiChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$sessionId': typeof ChatSessionIdLazyRoute
  '/api/chat': typeof ApiChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/$sessionId': typeof ChatSessionIdLazyRoute
  '/api/chat/': typeof ApiChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat/$sessionId' | '/api/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$sessionId' | '/api/chat'
  id: '__root__' | '/' | '/chat/$sessionId' | '/api/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatSessionIdLazyRoute: typeof ChatSessionIdLazyRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatSessionIdLazyRoute: ChatSessionIdLazyRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
